services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: scs-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: scs-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: postgres:16
    container_name: scs-postgres
    environment:
      POSTGRES_USER: scs
      POSTGRES_PASSWORD: scs_password
      POSTGRES_DB: inventorydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  inventory-service:
    build:
      context: ../../services/inventory-service
    container_name: scs-inventory-service
    depends_on:
      - kafka
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/inventorydb"
      SPRING_DATASOURCE_USERNAME: "scs"
      SPRING_DATASOURCE_PASSWORD: "scs_password"

  shipment-service:
    build:
      context: ../../services/shipment-service
    container_name: scs-shipment-service
    depends_on:
      - kafka
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

volumes:
  postgres_data:
